version: "3.9"

services:

  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"

  student-service:
    build: ./student-service
    ports:
      - "8001:8001"

  teacher-service:
    build: ./teacher-service
    ports:
      - "8002:8002"

  department-service:
    build: ./department-service
    ports:
      - "8003:8003"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P00jitha*19