name: CMS CI Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Student Service
        run: docker build -t student-service ./student-service

      - name: Build Teacher Service
        run: docker build -t teacher-service ./teacher-service

      - name: Build Department Service
        run: docker build -t department-service ./department-service

      - name: Build API Gateway
        run: docker build -t api-gateway ./API-gateway