name: CMS Microservices CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Dependencies
        run: |
          pip install -r student-service/requirements.txt
          pip install -r teacher-service/requirements.txt
          pip install -r department-service/requirements.txt
          pip install -r api-gateway/requirements.txt

      - name: Build Docker Containers
        run: docker compose build
